### ISSUE TITLE
trying to compile on linux

### ISSUE THREAD

**Issue by rdthree** [d3cod3/GAmuza#1]
hi - this project looks absolutely amazing.  do you have any suggestions for compiling this on linux?  i know its setup for mac and xcode - but i'm hoping there is a chance.  thanks.

**Comment by d3cod3** [comment]
hi originalsurfmex,

i'm going to explain in detail here the code structure of GAmuza project, for you and for everyone possibly interested in collaborating over this issue.

Before i start with the technical details, i have to say that i'm really really interested in extend the GAmuza software for the linux territory (and for the windows too, but this will be another issue), and that i've created this software alone in my free time, no money of any kind behind this project, and because of that the developing process is not so fast and a lot of things needs to be made too, and this issue is, if not the most important, one of them.

So, let's talk about the GAmuza core:

The GAmuza code structure is basically composed by three blocks

1 - the OF block (openframeworks code based on a slightly modified OF 0.7.4, easy to port to other systems)
2 - the LUA binding system, based on LUA, LUABIND, ofxLua addon (all of it with some patches) with all the code binded inside the live coding system, obviously including the entire OF 0.7.4 library + a bunch of ofxAddons. (so this point relatively easy to port to other systems, except all the ofxAddons specifically written for OSX)
3 - the CARBON/COCOA objC block, the basic GUI structure, windows managing, menus, plus some other small details.

Like you can see the problematic block is the third, where a "port" means rewrite most of it for linux, choose a window managing environment, GTK2 maybe, and rewrite all this third block!

It's not exaggerate to say that is a lot of work, especially putting everything together working fine.

So,my answer to you is that there is hope, but need manpower.

If you have interest in participating, we can talk more, maybe found other people, and start to work together at GAmuza for linux, i do not have the same experience in linux software programming than in the OSX environment, but i learn fast!

Now i'm asking you, there is some hope to share this project? Creating a group of programmer and extend GAmuza?

And this is for everyone: and for windows too?

best

**Comment by rdthree** [comment]
yeah, this is way out of my league.  I hope others like the idea of porting to linux too though.  i did a little reading and came across the GNUstep project.  claim some linux compatibility with cocoa libs

http://www.gnustep.org/
